#!/bin/bash
PROJECT=systemd-shortcuts
GITHUB=lzap
TAG=$(git describe --abbrev=0 --tags)

mkdir -p rpmbuild/{BUILD,SRPM,RPM,SPECS,SOURCES}/
wget -q -c -N -P rpmbuild/SOURCES --no-check-certificate https://github.com/lzap/${PROJECT}/archive/${TAG}.tar.gz
rpmbuild --define "_topdir `pwd`/rpmbuild" -ba ${PROJECT}.spec
