#!/bin/bash
# systemd-shortcuts                                       -*- shell-script -*-
#
# This file is part of systemd-shortcuts
#
# Copyright 2014 Lukas Zapletal
#
# systemd is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or
# (at your option) any later version.
#
# systemd is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with systemd; If not, see <http://www.gnu.org/licenses/>.

die() {
  echo "$1" 1>&2; exit 1
}

ACTION=$1
shift

case $ACTION in
  help) man sysd ;;
  s|systemctl) systemctl $* ;;
  bootctl) bootctl $* ;;
  h|hostnamectl) hostnamectl $* ;;
  j|journalctl) journalctl $* ;;
  localectl) localectl $* ;;
  loginctl) loginctl $* ;;
  machinectl) machinectl $* ;;
  timedatectl) timedatectl $* ;;
  analyze) systemd-analyze $* ;;
  ask-password) systemd-ask-password $* ;;
  cat) systemd-cat $* ;;
  cgls) systemd-cgls $* ;;
  cgtop) systemd-cgtop $* ;;
  coredumpctl) systemd-coredumpctl $* ;;
  delta) systemd-delta $* ;;
  detect-virt) systemd-detect-virt $* ;;
  inhibit) systemd-inhibit $* ;;
  machine-id-setup) systemd-machine-id-setup $* ;;
  notify) systemd-notify $* ;;
  n|nspawn) systemd-nspawn $* ;;
  run) systemd-run $* ;;
  stdio-bridge) systemd-stdio-bridge $* ;;
  tmpfiles) systemd-tmpfiles $* ;;
  tty-ask-password-agent) systemd-tty-ask-password-agent $* ;;
  lscg) systemd-cgls $* ;;
  topcg) systemd-cgtop $* ;;
  *) die "$0: unrecognized option '$ACTION'" ;;
esac

# vim:sw=2:ts=2:et:ft=sh:
